### ISSUE TITLE
read-only switch for the editor

### ISSUE THREAD

**Issue by nyanlathotep** [dox4242/RG-tools#20]
I'm not terribly sold on the necessity of the idea, but adding a way to make the editor read-only might be nice.

If added, this setting should probably persist in localstorage.

**Comment by nyanlathotep** [comment]
With no expressed interest, just gonna close this. If anyone wants to disable exporting, this user style along with a manager like Stylish [(chrome)](https://chrome.google.com/webstore/detail/stylish-custom-themes-for/fjnbnpbmkenffdnngjfgmeleoegfcffe?hl=en) [(firefox)](https://addons.mozilla.org/en-US/firefox/addon/stylish/) will remove the output field.

```css
@-moz-document domain("dox4242.github.io") {
	.input-group:nth-of-type(2) {
		display: none;
	}
}
```
